### ISSUE TITLE
configuration error :ign-fuel-tools

### ISSUE THREAD

**Issue by Anusha-jain-h-c** [ignitionrobotics/ign-fuel-tools#88] opened 2020-07-20 12:55 UTC
```
C:\Users\abdhi>git clone https://github.com/ignitionrobotics/ign-fuel-tools -b ign-fuel-tools1
Cloning into 'ign-fuel-tools'...
remote: Enumerating objects: 176, done.
remote: Counting objects: 100% (176/176), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 5593 (delta 90), reused 93 (delta 40), pack-reused 5417
Receiving objects: 100% (5593/5593), 3.61 MiB | 2.50 MiB/s, done.
Resolving deltas: 100% (3936/3936), done.

C:\Users\abdhi>cd ign-fuel-tools

C:\Users\abdhi\ign-fuel-tools>.\configure

C:\Users\abdhi\ign-fuel-tools>call  :download_unzip_install curl-7.57.0-vc15-x64-dll-MD.zip
The system cannot find the batch label specified - download_unzip_install

C:\Users\abdhi\ign-fuel-tools>call  :download_unzip_install jsoncpp-1.8.4-vc15-x64-dll-MD.zip
The system cannot find the batch label specified - download_unzip_install

C:\Users\abdhi\ign-fuel-tools>call  :download_unzip_install libyaml-0.1.7-vc15-x64-md.zip
The system cannot find the batch label specified - download_unzip_install

C:\Users\abdhi\ign-fuel-tools>call  :download_unzip_install libzip-1.4.0_zlip-1.2.11_vc15-x64-dll-MD.zip
The system cannot find the batch label specified - download_unzip_install

C:\Users\abdhi\ign-fuel-tools>call  :install_ign_project ign-common ign-common1
The system cannot find the batch label specified - install_ign_project
Configuring for build type Release

C:\Users\abdhi\ign-fuel-tools>cd /d C:\Users\abdhi\ign-fuel-tools\

C:\Users\abdhi\ign-fuel-tools>md build

C:\Users\abdhi\ign-fuel-tools>cd build

C:\Users\abdhi\ign-fuel-tools\build>cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=""install\Release"" -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING:BOOL=False
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findignition-cmake0.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-cmake0", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-cmake0"
  (requested version 0.4.1) with any of the following names:

    ignition-cmake0Config.cmake
    ignition-cmake0-config.cmake

  Add the installation prefix of "ignition-cmake0" to CMAKE_PREFIX_PATH or
  set "ignition-cmake0_DIR" to a directory containing one of the above files.
  If "ignition-cmake0" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/Users/abdhi/ign-fuel-tools/build/CMakeFiles/CMakeOutput.log".
C:\Users\abdhi\ign-fuel-tools\build>
```

I am getting same error for every other ign installations. Please help me ..I am trying to install it in windows 10.

**Comment by chapulina** [comment] 2020-07-20 18:51
This issue is a duplicate of https://github.com/ignitionrobotics/ign-msgs/issues/72, so I'll close this one since that one already has some conversation going.

**Closed** 2020-07-20 18:51 UTC
