### ISSUE TITLE
`uriToPath` function returns a colon in Windows

### ISSUE THREAD

**Issue by Blast545** [ignitionrobotics/ign-fuel-tools#204] opened 2021-09-10 14:47 UTC
## Environment
* Windows, source

## Description
* Expected behavior: `uriToPath` function shouldn't return the `:` character in windows.
* Actual behavior: It doesn't strip it. Follow up issue to the discussion in [this comment](https://github.com/ignitionrobotics/ign-fuel-tools/pull/201#issuecomment-912719454).

Before the discussion, this [ci error](https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/66/testReport/junit/(root)/HelpersTEST/UriToPathNoAuthority/) tracks the error in CI where the output of `joinPaths` strips the character and the `uriToPath` doesn't. 

The error doesn't occur when the authority is set, because in that case the `joinPath` function is called at the end. See [Helpers.cc#66](https://github.com/ignitionrobotics/ign-fuel-tools/blob/57aaf43f77b2e63ed11171c5e95c2bcfe9dc0e0d/src/Helpers.cc#L56)

## Steps to address this issue
- [ ]  Explicitly define expected input and output for the `uriToPath` function.
- [ ]  Update the uriToPath function accordingly.
- [ ]  Modify the tests in `Helpers_TEST.cc` accordignly.

**Comment by chapulina** [comment] 2021-12-29 19:11
Just noticed this is a duplicate of https://github.com/ignitionrobotics/ign-fuel-tools/issues/106

**Closed by chapulina** 2021-12-29 19:11 UTC
Labels: bug, help wanted, Windows
